production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: <%= ENV["424916814044-d37rqpp71p012pk6gub73e016hbtd3g5.apps.googleusercontent.com"] %>
  GOOGLE_SECRET_KEY: <%= ENV["xKHcarFV6r3oqOOXl9FQNuqh"] %>